module.exports = {
    Accuracy: require('./src/Accuracy'),
    Beatmap: require('./src/Beatmap'),
    Circle: require('./src/Circle'),
    CursorData: require('./src/CursorData'),
    HitObject: require('./src/HitObject'),
    MapInfo: require('./src/MapInfo'),
    MapPP: require('./src/MapPP'),
    MapStars: require('./src/MapStars'),
    MapStats: require('./src/MapStats'),
    mods: require('./src/mods'),
    objectTypes: require('./src/constants/objectTypes'),
    Parser: require('./src/Parser'),
    Player: require('./src/Player'),
    ppv2: require('./src/ppv2'),
    rankImage: require('./src/rankImage'),
    ReplayAnalyzer: require('./src/ReplayAnalyzer'),
    ReplayData: require('./src/ReplayData'),
    ReplayObjectData: require('./src/ReplayObjectData'),
    Score: require('./src/Score'),
    Slider: require('./src/Slider'),
    StandardDiff: require('./src/StandardDiff'),
    StandardDiffHitObject: require('./src/StandardDiffHitObject'),
    Timing: require('./src/Timing'),

    gamemode: require('./src/constants/gamemode'),
    hitResult: require('./src/constants/hitResult'),
    modes: require('./src/constants/modes'),
    movementType: require('./src/constants/movementType'),
    rankedStatus: require('./src/constants/rankedStatus'),
};