/**
 * Symbols used throughout the bot.
 */
export enum Symbols {
    cross = "❎",
    checkmark = "✅",
    exclamationMark = "❗",
    skipBackward = "⏮️",
    leftArrow = "⬅️",
    rightArrow = "➡️",
    downArrow = "⬇️",
    upArrow = "⬆️",
    skipForward = "⏭️",
    thumbsUp = "👍",
    thumbsDown = "👎",
    star = "★",
    rightArrowSmall = "▸",
    missIcon = "❌",
    upIcon = "🆙",
    cake = "🎂",
    timer = "⏲️",
    repeatSingleButton = "🔂",
    heart = "❤️",
    playButton = "▶️",
    memo = "📝",
    crown = "👑",
    personRunning = "🏃",
    inboxTray = "📥",
    magnifyingGlassTiltedRight = "🔎",
    wavingHand = "👋",
    lockWithKey = "🔐",
    bookmarkTabs = "📑",
    barChart = "📊",
    framedPicture = "🖼️",
}
