/**
 * Constants for beatmap parser.
 */
export enum ParserConstants {
    MAX_PARSE_VALUE = 2147483647,

    MAX_COORDINATE_VALUE = 131072,

    MIN_REPETITIONS_VALUE = 0,
    MAX_REPETITIONS_VALUE = 9000,

    MIN_DISTANCE_VALUE = 0,
    MAX_DISTANCE_VALUE = 131072,

    MIN_SPEEDMULTIPLIER_VALUE = 0.1,
    MAX_SPEEDMULTIPLIER_VALUE = 10,

    MIN_MSPERBEAT_VALUE = 6,
    MAX_MSPERBEAT_VALUE = 60000,
}
