import { Localization } from "@alice-localization/base/Localization";
import { Translations } from "@alice-localization/base/Translations";
import { ClanENTranslation } from "./translations/ClanENTranslation";
import { ClanESTranslation } from "./translations/ClanESTranslation";
import { ClanKRTranslation } from "./translations/ClanKRTranslation";

export interface ClanStrings {
    readonly notInMainGuild: string;
    readonly selfIsNotInClan: string;
    readonly selfIsAlreadyInClan: string;
    readonly userIsNotInClan: string;
    readonly userIsAlreadyInClan: string;
    readonly selfHasNoAdministrativePermission: string;
    readonly userIsAlreadyCoLeader: string;
    readonly userIsNotCoLeader: string;
    readonly noActiveAuctions: string;
    readonly noAvailableClans: string;
    readonly userIsNotInExecutorClan: string;
    readonly selfInBattleCooldown: string;
    readonly userInBattleCooldown: string;
    readonly selfNotInBattleCooldown: string;
    readonly userNotInBattleCooldown: string;
    readonly selfInOldJoinCooldown: string;
    readonly userInOldJoinCooldown: string;
    readonly selfNotInOldJoinCooldown: string;
    readonly userNotInOldJoinCooldown: string;
    readonly selfInJoinCooldown: string;
    readonly userInJoinCooldown: string;
    readonly selfNotInJoinCooldown: string;
    readonly userNotInJoinCooldown: string;
    readonly roleIconIsNotUnlocked: string;
    readonly roleColorIsNotUnlocked: string;
    readonly cannotDownloadRoleIcon: string;
    readonly invalidRoleIconURL: string;
    readonly roleIconFileSizeTooBig: string;
    readonly invalidRoleIconSize: string;
    readonly clanPowerNotEnoughToBuyItem: string;
    readonly shopItemIsUnlocked: string;
    readonly noSpecialClanShopEvent: string;
    readonly invalidClanRoleHexCode: string;
    readonly clanRoleHexCodeIsRestricted: string;
    readonly clanDoesntHaveClanRole: string;
    readonly clanAlreadyHasClanRole: string;
    readonly clanAlreadyHasChannel: string;
    readonly powerupGachaNoResult: string;
    readonly powerupGachaWin: string;
    readonly powerupActivateInMatchMode: string;
    readonly powerupIsAlreadyActive: string;
    readonly clanDoesntHavePowerup: string;
    readonly clanAuctionHasBeenBid: string;
    readonly invalidClanAuctionAmount: string;
    readonly clanAuctionAmountOutOfBounds: string;
    readonly invalidClanAuctionMinimumBid: string;
    readonly invalidClanAuctionDuration: string;
    readonly invalidClanAuctionBidAmount: string;
    readonly buyShopItemConfirmation: string;
    readonly createClanConfirmation: string;
    readonly leaveClanConfirmation: string;
    readonly disbandClanConfirmation: string;
    readonly kickMemberConfirmation: string;
    readonly removeIconConfirmation: string;
    readonly removeBannerConfirmation: string;
    readonly editDescriptionConfirmation: string;
    readonly clearDescriptionConfirmation: string;
    readonly promoteMemberConfirmation: string;
    readonly demoteMemberConfirmation: string;
    readonly acceptClanInvitationConfirmation: string;
    readonly activatePowerupConfirmation: string;
    readonly clanAuctionCancelConfirmation: string;
    readonly clanAuctionCreateConfirmation: string;
    readonly clanAuctionBidConfirmation: string;
    readonly clanPowerTransferConfirmation: string;
    readonly clanNameIsTooLong: string;
    readonly clanAuctionNameIsTooLong: string;
    readonly clanNameHasUnicode: string;
    readonly notEnoughCoins: string;
    readonly clanNameIsTaken: string;
    readonly clanDoesntExist: string;
    readonly auctionDoesntExist: string;
    readonly auctionNameIsTaken: string;
    readonly userToTransferFromNotInClan: string;
    readonly userToTransferToNotInClan: string;
    readonly clanToTransferFromNotInMatchMode: string;
    readonly clanToTransferToNotInMatchMode: string;
    readonly clanHasPowerupActive: string;
    readonly profileNotFound: string;
    readonly clanUpkeepInformation: string;
    readonly clanDescriptionTooLong: string;
    readonly createClanSuccessful: string;
    readonly leaveClanFailed: string;
    readonly leaveClanSuccessful: string;
    readonly setClanMatchModeFailed: string;
    readonly setClanMatchModeSuccess: string;
    readonly disbandClanFailed: string;
    readonly disbandClanSuccessful: string;
    readonly kickMemberFailed: string;
    readonly kickMemberSuccessful: string;
    readonly setIconFailed: string;
    readonly setIconSuccessful: string;
    readonly setBannerFailed: string;
    readonly setBannerSuccessful: string;
    readonly removeIconFailed: string;
    readonly removeIconSuccessful: string;
    readonly removeBannerFailed: string;
    readonly removeBannerSuccessful: string;
    readonly modifyClanPowerFailed: string;
    readonly modifyClanPowerSuccessful: string;
    readonly editDescriptionFailed: string;
    readonly editDescriptionSuccessful: string;
    readonly clearDescriptionFailed: string;
    readonly clearDescriptionSuccessful: string;
    readonly buyShopItemFailed: string;
    readonly buyShopItemSuccessful: string;
    readonly promoteMemberFailed: string;
    readonly promoteMemberSuccessful: string;
    readonly demoteMemberFailed: string;
    readonly demoteMemberSuccessful: string;
    readonly acceptClanInvitationFailed: string;
    readonly acceptClanInvitationSuccessful: string;
    readonly activatePowerupFailed: string;
    readonly activatePowerupSuccessful: string;
    readonly clanAuctionCancelFailed: string;
    readonly clanAuctionCancelSuccessful: string;
    readonly clanAuctionCreateFailed: string;
    readonly clanAuctionCreateSuccessful: string;
    readonly clanAuctionBidFailed: string;
    readonly clanAuctionBidSuccessful: string;
    readonly clanPowerTransferFailed: string;
    readonly clanPowerTransferSuccessful: string;
    readonly changeRoleColorSuccessful: string;
    readonly changeRoleIconSuccessful: string;
    readonly createClan: string;
    readonly clanChannel: string;
    readonly clanPowerup: string;
    readonly clanRename: string;
    readonly clanRole: string;
    readonly clanRoleColorUnlock: string;
    readonly clanRoleIconUnlock: string;
    readonly leadershipTransfer: string;
    readonly buyShopItem: string;
    readonly bidToAuction: string;
    readonly auctionInfo: string;
    readonly auctionName: string;
    readonly auctionAuctioneer: string;
    readonly creationDate: string;
    readonly expirationDate: string;
    readonly auctionItem: string;
    readonly auctionPowerup: string;
    readonly auctionAmount: string;
    readonly auctionMinimumBid: string;
    readonly auctionBidders: string; // look at 63.38 later
    readonly auctionBidInfo: string;
    readonly activePowerups: string;
    readonly ownedPowerups: string;
    readonly guidelineWebsite: string;
    readonly clanLeader: string;
    readonly clanPower: string;
    readonly clanMemberCount: string;
    readonly clanTotalUpkeepEstimation: string;
    readonly clanName: string;
    readonly discordId: string;
    readonly clanMemberRole: string;
    readonly clanMemberRoleLeader: string;
    readonly clanMemberRoleCoLeader: string;
    readonly clanMemberRoleMember: string;
    readonly clanMemberUpkeepValue: string;
    readonly announceModalTitle: string;
    readonly announceModalMessageLabel: string;
    readonly announceModalMessagePlaceholder: string;
}

/**
 * Localizations for the `clan` command.
 */
export class ClanLocalization extends Localization<ClanStrings> {
    protected override readonly localizations: Readonly<
        Translations<ClanStrings>
    > = {
        en: new ClanENTranslation(),
        kr: new ClanKRTranslation(),
        es: new ClanESTranslation(),
    };
}
